config/routes.rb
Rails.application.routes.draw do
  resources :examples

  devise_for :users
	resources :circle

end

app/models/circle.rb
class Circle < ActiveRecord::Base
	has_many :users
	belongs_to :owner, class_name: "User", foreign_key: "owner_id"
	validates :owner, presence: true
	validates :name, presence: true
end

app/models/example.rb
class Example < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable
	devise :database_authenticatable, :registerable,
		:recoverable, :rememberable, :trackable, :validatable,
		:omniauthable, :omniauth_providers => [:facebook, :google_oauth2]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/circle_controller.rb
class CircleController < ApplicationController
	def index
		@circles = Circle.all
	end

	def new
		@circle = Circle.new
	end
end

app/controllers/examples_controller.rb
class ExamplesController < ApplicationController
  before_action :set_example, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @examples = Example.all
    respond_with(@examples)
  end

  def show
    respond_with(@example)
  end

  def new
    @example = Example.new
    respond_with(@example)
  end

  def edit
  end

  def create
    @example = Example.new(example_params)
    @example.save
    respond_with(@example)
  end

  def update
    @example.update(example_params)
    respond_with(@example)
  end

  def destroy
    @example.destroy
    respond_with(@example)
  end

  private
    def set_example
      @example = Example.find(params[:id])
    end

    def example_params
      params[:example]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/circle_helper.rb
module CircleHelper
end

app/helpers/examples_helper.rb
module ExamplesHelper
end

app/views/circle/index.erb
<%= @circles %>
<%= link_to "new", new_circle_path %>

app/views/circle/new.erb
<%= form_for @circle do |circle| %>
  <input type="text"/>
<% end %>

app/views/examples/_form.html.erb
<%= form_for(@example) do |f| %>
  <% if @example.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@example.errors.count, "error") %> prohibited this example from being saved:</h2>

      <ul>
      <% @example.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/examples/edit.html.erb
<h1>Editing example</h1>

<%= render 'form' %>

<%= link_to 'Show', @example %> |
<%= link_to 'Back', examples_path %>

app/views/examples/index.html.erb
<h1>Listing examples</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @examples.each do |example| %>
      <tr>
        <td><%= link_to 'Show', example %></td>
        <td><%= link_to 'Edit', edit_example_path(example) %></td>
        <td><%= link_to 'Destroy', example, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Example', new_example_path %>

app/views/examples/new.html.erb
<h1>New example</h1>

<%= render 'form' %>

<%= link_to 'Back', examples_path %>

app/views/examples/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_example_path(@example) %> |
<%= link_to 'Back', examples_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Friendzone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>